server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:

  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: syslogs
        __path__: /var/log/syslog

  - job_name: docker-logs
    static_configs:
    - targets:
        - localhost
      labels: 
        job: container
        host: docker
        __path__: /var/lib/docker/containers/*/*-json.log
  
  - job_name: nginx-access-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx-access
        __path__: /var/log/nginx/access.log

  - job_name: nginx-error-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: nginx-error
        __path__: /var/log/nginx/error.log

  - job_name: grafana-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: grafana
        __path__: /var/log/grafana/grafana.log
