---
- name: Download script for apt repo add
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: '0755'

- name: Add gitlab-runner repository
  ansible.builtin.shell: /tmp/script.deb.sh

- name: Install gitlab-runner
  ansible.builtin.apt:
    name:
      - gitlab-runner
    update_cache: true

- name: Register a runner
  shell: gitlab-runner register --non-interactive --executor "shell" --shell "bash" --url "{{ gitlab_url }}" --token "{{ gitlab_token }}"

- name: Setup runner permissions
  shell: usermod -aG docker gitlab-runner

- name: Create sudo permissions file for runner
  ansible.builtin.file:
    path: /etc/sudoers.d/gitlab-runner
    state: touch
    owner: root
    group: root
    mode: u=r,g=r

- name: Update sudo permissions for runner
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/gitlab-runner
    line: gitlab-runner ALL=(ALL) NOPASSWD:ALL
    state: present

- name: Create new environment file
  ansible.builtin.copy:
    src: environment
    dest: /var/environment
    owner: root
    group: docker
    mode: u=rw,g=rw
    ignore_errors: true

- name: Verify a runner
  shell: gitlab-runner verify
