---
# tasks file for stage
- name: Include docker install
  ansible.builtin.include_tasks: install-docker.yml

- name: Include gitlab-runner setup
  ansible.builtin.include_tasks: install-gitlab-runner.yml
  when: gitlab_install == True

- name: Include monitoring setup
  ansible.builtin.include_tasks: monitoring-setup.yml

- name: Include ansible install
  ansible.builtin.include_tasks: install-ansible.yml

- name: Include monitoring reverse proxy setup
  ansible.builtin.include_tasks: reverse-proxy-monitoring.yml

- name: Include logging setup
  ansible.builtin.include_tasks: logging-setup.yml
