# install docker exporter?
# paste prometheus & alertmanager config

---
- name: Install grafana dependencies
  ansible.builtin.apt:
   name:
    - apt-transport-https
    - software-properties-common
    - wget

- name: Ensure keyrings directory is present
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

# По политеческим причинам графана блокирует доступ к некоторым странам, поэтому приложение будет установлено вручную С:
#- name: Add grafana gpg key
#  ansible.builtin.apt_key:
#    url: https://apt.grafana.com/gpg.key
#    state: present
#    keyring: /etc/apt/keyrings/grafana.gpg
#
#- name: Add grafana gpg key manualy
#  ansible.builtin.template:
#    src: grafana/grafana.gpg
#    dest: /etc/apt/keyrings/grafana.gpg
#    owner: root
#    group: root
#    mode: u=rw,g=r,o=r
#
#- name: Add grafana stable release repository
#  ansible.builtin.apt_repository:
#    filename: grafana
#    repo: deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
#    state: present
#
- name: Copy deb package to target machine
  ansible.builtin.copy:
    src: grafana.deb
    dest: /tmp/grafana.deb

- name: Install Grafana
  ansible.builtin.apt:
    deb: /tmp/grafana.deb

- name: Start grafana server
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: grafana-server.service
    state: started
    enabled: true

- name: Install monitoring apps
  ansible.builtin.apt:
    name:
      - prometheus
      - prometheus-alertmanager
    update_cache: true

- name: Copy promethus cfg file
  ansible.builtin.template:
    src: prometheus/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy app monitoring rules file
  ansible.builtin.copy:
    src: prometheus/app_rules.yml
    dest: /etc/prometheus/app_rules.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy basic monitoring rules file
  ansible.builtin.copy:
    src: prometheus/basic_rules.yml
    dest: /etc/prometheus/basic_rules.yml
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Apply monitoring rules
  ansible.builtin.systemd_service:
    name: prometheus.service
    state: restarted