---
groups:
- name: app monitoring rules
  rules:

  - alert: AppIsDown
    expr: absent(up{job="app"})
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: App is down on (instance {{ $labels.instance }})
      description: "App is down for somereasone\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"